### ISSUE TITLE
V1 of webcomponents

### ISSUE THREAD

**Issue by ghost** [jonboj/mdcdalight#2]
So we are relying on the dart team for V1 of webcomponents.

Also can you add a link for what browsers support it ? For v1 I mean

**Comment by jonboj** [comment]
Web components are a collection of features, with Custom elements as core feature.
https://caniuse.com/#search=custom%20elements

>So we are relying on the dart team for V1 of webcomponents.

On a very rough/simple scale mdcdalight is an integration between dart-sdk, web components and mdc web. So yes within this scale this rely on an implementation of web components in dart-sdk.

Since mdcdalight was put on github, the mdc web project has matured a lot and got several off springs. Like this project, which integrates Web components and mdc web https://github.com/material-components/material-components-web-components
If this matures and dart-sdk adds support for web components v1, then maybe more reasonable to use this and maybe just reuse some of the binding framework from mdcdalight.

I will close the issue, but thanks for your interest and attention.
